/* Clean question set: all language fields are explicit; no fallback is used. */
(()=>{
 const A={
 ku:['ئەم هێمایە چی مانایە؟',['وەستانی تەواو','ڕێ بدە','سنووری خێرایی ٤٠','سنووری خێرایی ٦٠','چوونەژوورەوە قەدەغەیە','پارکینگ','پارک کردن قەدەغەیە','شوێنی پێڕەوان','ئاگاداری قوتابخانە','گەرەکی','بەڕەو ڕاست','سوڕانەوە بۆ ڕاست قەدەغەیە','کار لەسەر ڕێگا','ڕێگای خلیسک','چوارڕێگا','چرای هاتووچۆ','بەرزبوونەوەی ڕێگا','ڕێگا تەنگ دەبێتەوە','ڕێی شەمەندەفەر','ڕێگای یەک ئاراستە']],
 bad:['ئە ڤ نیشانە چی مانایە؟',['تەمام راوەستە','رێ بدە','سنوورا خێرایی ٤٠','سنوورا خێرایی ٦٠','چوونەژوور قەدەغەیە','پارکینگ','پارک قەدەغەیە','شوێنا پیادەڕەوان','ئاگاداری قوتابخانە','گەردوونە','بەرەڤ راست','پیچ بەرەڤ راست قەدەغەیە','کار ل سەر رێکێ','رێکا خلیسک','چواررێ','چرایا ترافیکی','بەرزبوونا رێکێ','رێک تنگ دبیت','رێیێ شەمەندەفەر','یەک ئاراستە']],
 ar:['ماذا تعني هذه الإشارة؟',['توقف تام','أعطِ الأفضلية','الحد الأقصى للسرعة ٤٠','الحد الأقصى للسرعة ٦٠','ممنوع الدخول','موقف سيارات','ممنوع الوقوف','ممر المشاة','تحذير: مدرسة','دوار','اتجه يميناً','ممنوع الانعطاف يميناً','أعمال طريق','طريق زلق','تقاطع','إشارة ضوئية أمامك','مطب','الطريق يضيق','سكة حديد','اتجاه واحد']],
 tr:['Bu işaret ne anlama gelir?',['Tam dur','Yol ver','Azami hız 40','Azami hız 60','Giriş yasaktır','Otopark','Park etmek yasaktır','Yaya geçidi','Okul uyarısı','Dönel kavşak','Sağa dön','Sağa dönüş yasaktır','Yol çalışması','Kaygan yol','Kavşak','Trafik ışıkları','Kasis','Yol daralıyor','Demiryolu','Tek yön']],
 fa:['این علامت چه معنی دارد؟',['توقف کامل','حق تقدم بدهید','حداکثر سرعت ۴۰','حداکثر سرعت ۶۰','ورود ممنوع','پارکینگ','پارک ممنوع','گذرگاه عابر پیاده','هشدار مدرسه','میدان','به راست بروید','گردش به راست ممنوع','عملیات جاده‌ای','جاده لغزنده','چهارراه','چراغ راهنمایی جلوتر','دست‌انداز','جاده باریک می‌شود','خط راه‌آهن','یک‌طرفه']],
 en:['What does this sign mean?',['Stop completely','Give way','Maximum speed 40','Maximum speed 60','No entry','Parking','No parking','Pedestrian crossing','School warning','Roundabout','Turn right','No right turn','Road works','Slippery road','Crossroads','Traffic lights ahead','Road hump','Road narrows','Railway crossing','One way']]
 };
 const bank=[]; const langs=Object.keys(A);
 for(let i=0;i<20;i++){const q={id:`official-sign-${i+1}`,answer:0,image:`assets/badini-pdf/sign-${String(i+1).padStart(3,'0')}.png`,official:true};for(const l of langs){const x=A[l];q[l]={q:x[0],choices:[x[1][i],x[1][(i+6)%20],x[1][(i+13)%20]]};}bank.push(q)}
 const R=[
 [['لە باراندا چی دەکەیت؟','فاصڵەی ئاسایی زیاد بکە','خێرایی زیاد بکە','چراغەکان کوژێنەوە'],['دەمێ بارانێدا چی بکەی؟','مەودایا ئێمنی زیاد بکە','خێرایی زیاد بکە','چرایان کوژێنەوە'],['عند المطر ماذا تفعل؟','زد مسافة الأمان','زد السرعة','أطفئ المصابيح'],['Yağmurda ne yapmalısınız?','Takip mesafesini artırın','Hızı artırın','Farları kapatın'],['هنگام باران چه می‌کنید؟','فاصله ایمن را بیشتر می‌کنید','سرعت را زیاد می‌کنید','چراغ‌ها را خاموش می‌کنید'],['What should you do in rain?','Increase following distance','Increase speed','Turn off lights']],
 [['لە پێڕەوەڕێدا چی دەکەیت؟','خێرایی کەم بکە و ڕێ بدە','خێرایی زیاد بکە','تەنها هۆرن لێبدە'],['د خەتێ پیادەڕەواندا چی بکەی؟','خێرایی کەم بکە و رێ بدە','خێرایی زیاد بکە','تەنێ هۆرن لێبدە'],['عند ممر المشاة ماذا تفعل؟','خفف السرعة وأعطِ المشاة الأولوية','زد السرعة','استخدم البوق فقط'],['Yaya geçidinde ne yaparsınız?','Yavaşlayıp yayalara yol verirsiniz','Hızı artırırsınız','Sadece korna çalarsınız'],['در گذرگاه عابر پیاده چه می‌کنید؟','سرعت را کم می‌کنید و حق تقدم می‌دهید','سرعت را زیاد می‌کنید','فقط بوق می‌زنید'],['What do you do at a pedestrian crossing?','Slow down and give way','Increase speed','Only sound the horn']],
 [['پێش گۆڕینی هێڵ چی دەکەیت؟','ئاوێنە و خاڵی کوێر بپشکنە','بێ سەیرکردن بگۆڕە','خێرایی زیاد بکە'],['بەری گوهۆڕینا لینێ چی بکەی؟','ئاوێنە و خاڵا کوێر بپشکنە','بێ سەیرکرن بگۆڕە','خێرایی زیاد بکە'],['قبل تغيير المسار ماذا تفعل؟','افحص المرايا والنقطة العمياء','غيّر دون نظر','زد السرعة'],['Şerit değiştirmeden önce ne yaparsınız?','Aynaları ve kör noktayı kontrol edin','Bakmadan değiştirin','Hızı artırın'],['پیش از تغییر خط چه می‌کنید؟','آینه‌ها و نقطه کور را بررسی کنید','بدون نگاه تغییر دهید','سرعت را زیاد کنید'],['What do you do before changing lanes?','Check mirrors and blind spot','Change without looking','Increase speed']],
 [['کاتێک ماندوو دەبیت چی دەکەیت؟','لە شوێنێکی سەلامەت بوەستە و پشووبدە','خێرایی زیاد بکە','بەردەوام بە'],['دەمێ خەوتی بیت چی بکەی؟','راوەستە و پشوویێ بدە','خێرایی زیاد بکە','بەردەوام بە'],['عند الشعور بالتعب ماذا تفعل؟','توقف في مكان آمن واسترح','زد السرعة','واصل القيادة'],['Yorgunken ne yapmalısınız?','Güvenli yerde durup dinlenin','Hızı artırın','Devam edin'],['وقتی خسته هستید چه می‌کنید؟','در جای امن توقف و استراحت کنید','سرعت را زیاد کنید','ادامه دهید'],['What should you do when tired?','Stop safely and rest','Increase speed','Keep driving']],
 [['کاتێک ئەمبولانس نزیک دەبێتەوە چی دەکەیت؟','بە سەلامەتی ڕێ بدە','ڕێ مەدە','دوای بکەوە'],['دەمێ ئەمبولانس نزیک دەبیت چی بکەی؟','ب سەلامەتی رێ بدە','رێ مەدە','دوای بکەوە'],['عند اقتراب سيارة إسعاف ماذا تفعل؟','افسح الطريق بأمان','لا تفسح الطريق','اتبعها'],['Ambulans yaklaşınca ne yaparsınız?','Güvenle yol verin','Yol vermeyin','Onu takip edin'],['وقتی آمبولانس نزدیک می‌شود چه می‌کنید؟','با ایمنی راه بدهید','راه ندهید','دنبالش بروید'],['What do you do when an ambulance approaches?','Give way safely','Do not give way','Follow it']],
 [['چرای سور چی دەڵێت؟','وەستانی تەواو','خێرایی زیاد بکە','پێش بکەوە'],['چرایا سور چی دڵێت؟','تەمام راوەستە','خێرایی زیاد بکە','بەردەوام بە'],['ماذا يعني الضوء الأحمر؟','توقف تماماً','زد السرعة','تابع السير'],['Kırmızı ışık ne demektir?','Tam durun','Hızı artırın','Devam edin'],['چراغ قرمز چه معنی دارد؟','کاملاً توقف کنید','سرعت را زیاد کنید','حرکت کنید'],['What does a red traffic light mean?','Stop completely','Increase speed','Continue driving']],
 [['مۆبایل لەکاتی شوفێریدا؟','بەکارنەهێنە','بە دەست بەکاربێنە','هەمیشە بەکاریبهێنە'],['مۆبایل دەمێ شوفێریدا؟','بکارنەهێنە','ب دەست بکاربینە','هەردەم بکاربینە'],['الهاتف أثناء القيادة؟','لا تستخدمه بيدك','استخدمه بيدك','استخدمه دائماً'],['Sürüş sırasında telefon?','Elle kullanmayın','Elle kullanın','Her zaman kullanın'],['تلفن هنگام رانندگی؟','با دست استفاده نکنید','با دست استفاده کنید','همیشه استفاده کنید'],['Phone use while driving?','Do not use it by hand','Use it by hand','Always use it']],
 [['ئەگەر تایەر بترقێت چی دەکەیت؟','فەرمان بە ئارامی بگرە و خێرایی کەم بکە','برێکی توند بگرە','فەرمان توند بسووڕێنە'],['ئەگەر تایەر بترقیت چی بکەی؟','فەرمان ب ئارامی بگرە و خێرایی کەم بکە','برێکا توند بگرە','فەرمان توند بسوورینە'],['إذا انفجر الإطار ماذا تفعل؟','أمسك المقود بهدوء وخفف السرعة','اكبح بقوة','أدر المقود بعنف'],['Lastik patlarsa ne yaparsınız?','Direksiyonu sakin tutup hızı azaltın','Sert fren yapın','Direksiyonu sert çevirin'],['اگر لاستیک بترکد چه می‌کنید؟','فرمان را آرام نگه دارید و سرعت را کم کنید','محکم ترمز کنید','فرمان را ناگهانی بچرخانید'],['What do you do if a tyre bursts?','Hold the wheel calmly and slow down','Brake hard','Turn sharply']],
 [['پێش لێخوڕین چی پێویستە؟','هەموو کەس کەمەربەندی ئاسایی ببەستێت','تەنها شوفێر','هیچ کەس'],['بەری لێخوڕینێ چی پێدڤییە؟','هەمی کەس کەمەربەند ببەستن','تەنێ شوفێر','هیچ کەس'],['قبل القيادة ماذا يلزم؟','على الجميع ربط حزام الأمان','السائق فقط','لا أحد'],['Sürüşten önce ne gerekir?','Herkes emniyet kemeri takmalıdır','Sadece sürücü','Hiç kimse'],['پیش از رانندگی چه لازم است؟','همه کمربند ایمنی ببندند','فقط راننده','هیچ‌کس'],['What is required before driving?','Everyone must wear a seat belt','Only the driver','Nobody']],
 [['لە شەودا چۆن لێدەخوڕیت؟','چراغی گونجاو و خێرایی وریا بەکاربهێنە','بێ چراغ برۆ','هەمیشە چراغی بەرز'],['د شەڤێدا چۆن لێبخوڕی؟','چرایێن گونجاو و خێراییا وریا بکاربینە','بێ چرا بچە','هەردەم چرای بەرز'],['كيف تقود ليلاً؟','استخدم أضواء مناسبة وسرعة حذرة','قد دون أضواء','استخدم العالي دائماً'],['Gece nasıl sürersiniz?','Uygun far ve dikkatli hız kullanın','Farsız sürün','Her zaman uzun far'],['شب چگونه رانندگی می‌کنید؟','از چراغ مناسب و سرعت محتاطانه استفاده کنید','بدون چراغ برانید','همیشه نوربالا'],['How should you drive at night?','Use suitable lights and careful speed','Drive without lights','Always use high beams']]
 ];
 const safetyImages=['question-safety.svg','question-school.svg','question-signs.svg','safety-check.svg','question-ambulance.svg','question-stop.svg','question-phone.svg','question-safety.svg','question-seatbelt.svg','question-night.svg'];
 R.forEach((row,i)=>{const q={id:`official-rule-${i+1}`,answer:0,image:safetyImages[i],official:true};['ku','bad','ar','tr','fa','en'].forEach((l,n)=>q[l]={q:row[n][0],choices:row[n].slice(1)});bank.push(q)});
 window.CLEAN_OFFICIAL_BANK=bank;
})();
